# Generated by Django 3.1.1 on 2020-09-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200930_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default_book.jpg', upload_to='book_covers/'),
        ),
    ]
