# Generated by Django 3.1.1 on 2020-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201009_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
