# Generated by Django 3.1.1 on 2020-10-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='description',
            new_name='text',
        ),
    ]
