# Generated by Django 3.1.1 on 2020-11-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20201121_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('id',)},
        ),
    ]
