# Generated by Django 3.1.1 on 2020-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfrow',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
    ]
