# Generated by Django 3.1.1 on 2020-10-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_shelfrow_num_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelfitem',
            old_name='shelfRow',
            new_name='shelf_row',
        ),
    ]
