# Generated by Django 3.1.1 on 2020-10-25 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelf', '0003_auto_20201025_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfitem',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_shelf_row_item', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelfrow',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_shelf_row', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelf',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shelf', to=settings.AUTH_USER_MODEL),
        ),
    ]
