# Generated by Django 3.1.1 on 2020-10-30 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelf', '0004_auto_20201025_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfrow',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_shelf', to=settings.AUTH_USER_MODEL),
        ),
    ]
