# Generated by Django 3.1.1 on 2020-10-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20201030_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfrow',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
