# Generated by Django 3.1.1 on 2020-11-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_auto_20201030_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfitem',
            options={'ordering': ('id',)},
        ),
    ]
